import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/Organisme/Header";
import Footer from "../components/Organisme/Footer";
import Link from "next/link";

export default function About() {
  const [search, setSearch] = useState("");

  const HandleSearch = (e: any) => {
    e.preventDefault();
    const inputQuery = e.target[0].value;
    setSearch(inputQuery);
  };
  return (
    <>
      <Head>
        <title>MoshiDesu.Moe | API Anime</title>
        <meta name="description" content="Generated by Api Anime" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header HandleSearch={HandleSearch}></Header>
      <div className="mt-14 lg:mt-20">
        <h1 className="font-bangers text-3xl mb-4 text-center">About</h1>
        <div className="mx-4 lg:mx-[120px]">
          <div className="relative">
            <Image
              src={"/assets/about.png"}
              alt={""}
              width={100}
              height={100}
              className="absolute lg:-left-[82px] lg:-top-5 right-0 -top-24 lg:w-20 w-14 h-[96px] lg:h-[120px] mr-1"
            ></Image>
            <p>
              <Link href={"/"} className="font-bangers tracking-wide">
                {" "}
                Moshidesu.moe
              </Link>{" "}
              adalah situs jejaring sosial dan situs katalogisasi sosial
              menyangkut anime dan manga. Situs MoshiDesu.Moe terinspirasi dari
              Situs{" "}
              <Link
                href={"https://myanimelist.net/"}
                className="font-sans underline text-blue-600 tracking-wide"
              >
                {" "}
                MyAnimeList
              </Link>{" "}
              atau disingkat MAL dan memakai API dari JIKAN . Situs ini
              menyediakan sistem yang berupa daftar untuk mengatur dan menilai
              suatu anime dan manga. Hal memudahkan dalam menemukan pengguna
              dengan selera yang sama dan menyediakan database yang besar
              tentang anime dan manga. Pada tahun 2018, situs ini dikabarkan
              telah memiliki kira-kira 15.000 entri anime dan 45.000 entri
              manga. Pada tahun 2015, situs ini menerima 120 juta pengunjung per
              bulan
            </p>
            <br />
            <h1 className=" text-xl mb-1 font-bangers">Sejarah</h1>
            <p>
              Situs MyAnimeList diluncurkan pada bulan November 2004 oleh
              Garrett Gyssler dan dikelola sendiri sampai tahun 2008. Mulanya
              situs ini dipanggil dengan AnimeList, tetapi Garret Gyssler
              memutuskan untuk menggabungkan kata My di awal nama, mengikuti
              jejak dari jejaring sosial paling penting pada tahun-tahun itu:
              Myspace. Pada 4 Agustus 2008, CraveOnline, situs hiburan dan gaya
              hidup pria yang dimiliki oleh AtomicOnline, membeli MyAnimeList
              dengan uang yang dirahasiakan jumlahnya. Pada tahun 2015, DeNA
              mengumumkan bahwa mereka telah membeli MyAnimeList dari
              CraveOnline, dan bahwa mereka akan bekerjasama dengan Anime
              Consortium Japan untuk menyediakan layanan stream anime, melalui
              Daisuki. MyAnimeList mengumumkan pada bulan April 2016 bahwa
              mereka telah mencantumkan episode dari Crunchyroll dan Hulu
              langsung ke situsnya, dengan lebih dari 20.000 episode yang dibuat
              tersedia di situs tersebut. Pada 8 Maret 2018, MyAnimeList membuka
              toko manga online, bekerja sama dengan Kodansha Comics dan Viz
              Media, memungkinkan pengguna untuk membeli manga secara digital
              dari situs web. Layanan ini awalnya diluncurkan di Kanada tetapi
              kemudian diperluas ke Amerika Serikat, Inggris, dan beberapa
              negara berbahasa Inggris lainnya. Pada bulan April 2017,
              MyAnimeList menambahkan The King Avatar, suatu Animasi Tiongkok
              (Anime Cina) pada database situs ini. MAL menjadi tidak dapat
              diakses selama beberapa hari pada bulan Mei dan Juni 2018 ketika
              staf situs menjadikannya offline untuk pemeliharaan, dengan alasan
              keamanan dan privasi. Operator situs juga menonaktifkan API untuk
              aplikasi pihak ketiga, menjadikannya tidak dapat digunakan.
              Langkah itu dilakukan dalam upaya untuk menyesuaikan diri dengan
              program GDPR Uni Eropa. Pada Januari 2019, MyAnimeList diakuisisi
              oleh Media Do; dengan pembelian mereka, mereka mengumumkan niat
              mereka untuk fokus pada pemasaran dan penjualan e-book untuk
              memperkuat situs. Pada tanggal 25 September 2019, HIDIVE dan
              MyAnimeList mengumumkan kemitraan yang akan menggabungkan
              peringkat konten MyAnimeList ke dalam platform streaming HIDIVE,
              sementara secara eksklusif memberikan pengguna MyAnimeList pilihan
              pemilihan konten HIDIVE tertanam yang dikuratori secara gratis.
            </p>
          </div>
        </div>
      </div>
      <Footer></Footer>
    </>
  );
}
