import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { useState } from "react";
import { FaSearch } from "react-icons/fa";
import ResultSearch from "../components/ResultSearch";
import All from "../components/All";

export default function Home() {
  const [search, setSearch] = useState("");

  const HandleSearch = (e: any) => {
    e.preventDefault();
    const inputQuery = e.target[0].value;
    setSearch(inputQuery);
  };

  return (
    <>
      <Head>
        <title>MoshiDesu.Moe | API Anime</title>
        <meta name="description" content="Generated by Api Anime" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <div className="h-auto text-center">
        <form
          className="mx-4 items-center flex justify-center"
          onSubmit={HandleSearch}
        >
          <input
            type="text"
            placeholder="Cari Anime"
            className="lg:w-1/4 w-full tracking-wide focus:text-slate-800 px-4 py-2 ring-1 ring-slate-300 rounded-tl-xl rounded-bl-xl focus:shadow-md outline-gray-500 font-bangers font-light dark:text-white"
          />
          <button className="py-2 border-spacing-1 border-slate-200 px-3 items-center flex gap-x-1 bg-slate-800 dark:bg-white dark:text-black text-white rounded-tr-xl rounded-br-xl hover:bg-slate-600 font-bangers">
            Search<FaSearch></FaSearch>
          </button>
        </form>
      </div>
      {search ? <ResultSearch search={search}></ResultSearch> : <All></All>}
      <Footer></Footer>
    </>
  );
}
