import Head from "next/head";
import Header from "../components/Organisme/Header";
import Footer from "../components/Organisme/Footer";
import { useState, useEffect } from "react";
import HomePage from "../components/Organisme/HomePage";
import ResultSearch from "../components/Organisme/ResultSearch";
import Welcome from "../components/Atom/loading/welcome";
import { useRouter } from "next/router";

export default function Home() {
  const [search, setSearch] = useState("");
  // const [isWelcome, setWelcome] = useState(true);

  const HandleSearch = (e: any) => {
    e.preventDefault();
    const inputQuery = e.target[0].value;
    setSearch(inputQuery);
  };

  // useEffect(() => {
  //   setTimeout(() => {
  //     setWelcome(false);
  //   }, 5000);
  // });

  // if (isWelcome) {
  //   return <Welcome></Welcome>;
  // }

  return (
    <>
      <Head>
        <title>MoshiDesu.Moe | API Anime</title>
        <meta name="description" content="Generated by Api Anime" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header HandleSearch={HandleSearch}></Header>
      {search ? (
        <ResultSearch search={search} value={"anime"}></ResultSearch>
      ) : (
        <HomePage></HomePage>
      )}
      <Footer></Footer>
    </>
  );
}
