name: Cypress Test

on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Cypress Test
        uses: cypress-io/github-action@v5.0.5
        with:
          build: npm run build
          start: npm start
