name: Cypress Test

on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Cypress.io
        uses: cypress-io/github-action@v5.0.5
        with:
          spec: cypress/e2e/home.cy.ts
          start: npm start
          build: npm build
